permalink: /:categories/:year-:month-:day_:title/
timezone: Europe/Rome
encoding: utf-8

safe: true

markdown: kramdown
highlighter: rouge
lsi: false

kramdown:
  input             : GFM
  syntax_highlighter: rouge
  auto_ids          : true
  footnote_nr       : 1
  entity_output     : as_char
  toc_levels        : 1..6
  enable_coderay    : false
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line  : 1
