markdown: rdiscount
pygments: true
permalink: /:categories/:year:month:day_:title/

coderay:
coderay_wrap: div
coderay_line_numbers: inline
coderay_line_numbers_start: 1
coderay_tab_width: 2
coderay_bold_every: 10
coderay_css: style
